'use strict';

var errorCodes = {
    '001': 'Invalid username, username string must be at least 1 and maximum 32 characters.',
    '002': 'Username already exists.',
    '003': 'Missing user id',
    '004': 'Invalid user or user id',
    '005': 'Username not found',
    '006': 'Socket not found',
    '007': 'Address not found',
    '008': 'Token not found',
    '009': 'Invalid token',
    '010': 'The address is already used by the other users',
    '011': 'There is a password set for this withdraw address',
    '012': 'Already logged in',
    '013': 'Password check error',
    '014': 'Incorrect password',
    '015': 'User id not found or already has a socket',
    '016': 'That is a deposit address, don\'t do that',
    '017': 'Bitcoind error',
    '018': 'error creating user',
    '019': 'Invalid password. It must be at least 10 and maximum 64 characters long, and contains both alphabet and numeric characters only.',
    '020': 'Password hashing error',
    '021': 'User id not found',
    '022': 'Main address must be provided',
    '023': 'Invalid email token',
    '024': 'Email token not found',
    '025': 'Error clearing token',
    '026': 'Invalid amount',
    '027': 'Cannot withdraw less than',
    '028': 'Amount must be in satoshi',
    '029': 'Your balance is under 0.00005460 BTC',
    '030': 'Withdraw error',
    '031': 'Not all deposits have at least 1 confirmation',
    '032': 'Internal server error',
    '033': 'balance discrepency',
    '034': 'Error updating user',
    '035': 'No withdraw address for the currency',
    '036': 'Debit amount exceeds balance',
    '037': 'Message for the ticket not found',
    '038': 'Message not found',
    '039': 'Failed to send the message email',
    '040': 'No transaction reference id',
    '041': 'No transaction type',
    '042': 'Invalid amtIn/Out data',
    '043': 'Amounts cannot be negative, use amtIn to credit, amtOut to debit',
    '044': 'Cannot have amtIn and amtOut in the same transaction',
    '045': 'Invalid meta data JSON string',
    '046': 'refId already exists!',
    '047': 'No ticket found for the id provided',
    '048': 'The user does not have right to access this ticket',
    '049': 'No tickets',
    '050': 'Request invalid, missing ticket status parameter',
    '051': 'Request invalid, missing ticket id parameter',
    '052': 'Failed to send the ticket comment update email',
    '053': 'Missing withdraw address',
    '054': 'Missing password',
    '055': 'Invalid address',
    '056': 'Invalid signature',
    '057': 'Invalid API token header',
    '058': 'You must supply an API token',
    '059': 'No credentials found',
    '060': 'Invalid auth header',
    '061': 'You cannot access another user',
    '062': 'Invalid currency type',
    '063': 'Invalid main wallet address',
    '064': 'Invalid signature for main address',
    '065': 'Main wallet address should not be the same as the backup address',
    '066': 'Invalid backup wallet address',
    '067': 'Invalid signature for backup address',
    '068': 'Invalid format for withdraw amount',
    '069': 'Invalid original signature',
    '070': 'Invalid app key',
    '071': 'Invalid credit/debit action',
    '072': 'Account locked',
    '073': 'Invalid userIds parameter. userIds must be an array of user id',
    '074': 'Invalid email template name',
    '075': 'Invalid params',
    '076': 'You cannot access another user who are not your associate',
    '077': 'Incorrect One Time Password',
    '078': 'TOTP secret is undefined',
    '079': 'TOTP one time password is required'
};

module.exports = errorCodes;
