#!/usr/bin/env bash

[[ -d /data/primary/db ]] || mkdir /data/primary/db
chown -R mongodb:65535 /data
exec /sbin/setuser mongodb /usr/bin/mongod -f /data/primary/mongod.conf >> /var/log/mongod.log 2>&1

