'use strict';

// addresses to test with, these were generated by atticus, so
// anything sent to them will go to his dev wallet
// the message that was signed is 'foo'

module.exports = {
    bitcoin: {
        player: {
            address: "n2JYPHc11UuXZKKBmRWkgdYkEXbofKM3G2",
            signature: "IKqseiyfF+Qwh+cP9u2zKTxo9hBB7z6ke74zEZkukFl3AVhIBxUGI1xlNxjBzh5FMtqkF16xTyCHZyBp9YzqAAI="
        },
        playerUpdate: {
            address: "mwk9MY44s9GSungmxqziea7znmRESYDWZs",
            signature: "IOj9IMwxsUI4TnNjX4U9+WjekcPeo6THBJ64QTk0Li2v7HnDaTjJOeKyA/4V4vhHYE7oV5arV4ttTZw+qOse4xI="
        },
        playerBackup: {
            address: "mztuHc1Ldha7urwLg3uSPrZPYUr2bPPAZD",
            signature: "H7FRLf308lky+DWDA0kuFzyrwttkA3LhoZHTq5xABVSnKUXrjzA0oslGx1xE/RiNyBf3rrMslK79+ZZYEacyAMU="
        },
        playerBackupUpdate: {
            address: "mjygKYhQgVGUjQMhVSvBu7ih9fNE7zd6mv",
            signature: "ICd83ABIU4hbSrcQE+DUsDJwwDsN9RodUG7iMQZf17XK4s0oAWGM95LKjFF321S+FmLvH66JqKiVPZAz8ixEGhI="
        }
    },
    litecoin: {
        player: {
            address: "Lh2rD2Du8YPQuCd7mdymyShutLNVbnv9VY",
            signature: "ICxK/b0tMkN+FuXqR1WzdVbgXIB4IxSoj4MnFZZzTtcGv7vRbDubrdO3E21YB0VeNYw92jLNmCKKEh8LVAaLKOc="
        },
        playerUpdate: {
            address: "LMPXAfziXm63Efsag6jMxyym6491xUY1dh",
            signature: "IPp3H7o4M1uFxsGAKGzwvfpnLwI5aDHpBPrNDMjFM6+s54LFxxyNVRpNmnMGJBV86Vspbem2rfCG+dRV1yuEufA="
        },
        playerBackup: {
            address: "LP9D58ndJ8uWkZLwZXFA4wKoRzEQREiPzQ",
            signature: "IIsEfeTaOLWtxmcsTXNq0YoIb4kj2mkIL2mIHt+bIm+Nvo/wc16W/OLjEqBc9+PfqUWHIVNhE4A+zEIzv+EejRM="
        }
    },
    dogecoin: {
        player: {
            address: "DRdzC3XWrnVapuPXJdJ1BpQFDPZZ2Y86mH",
            signature: "HyuwEALivqCCAwxN2zu5rhgjIt76F/MmrJwiXP/nG7xqvSKWCDw4eHUBAb3965HgYc4uZ8OPqAXeAnqfQmsHRiA="
        },
        playerUpdate: {
            address: "D9sXZpf1zCW3n88DjQXYr9VJeaBGG1f3NN",
            signature: "IO3Npmm8kADxMgPO+/RVCHb5gKZHZJcWoCFGSrLKbiWNk6/cNyhBdkS77LjDW0ObHiOS6dzG4UkWr5LTq7Rvt2E="
        },
        playerBackup: {
            address: "DAHN11oRgndJ1zR7KiYbCQtjMTyc3iMdY2",
            signature: "H5s9A0J75F6lpmxZ6eoDuHoShTsIsGBM6MnD/Q16M4D4Cyc4QoSWSvzk0S7lF8dN0b1RqNl2Sh8cOKxQI1ydf20="
        }
    }
};
